#!/bin/sh

# 自定义初始化脚本
# 设置初始密码
echo -e "admin\nadmin" | passwd root >/dev/null 2>&1

# 启用无线
uci set wireless.radio0.disabled='0'
uci commit wireless

# 设置时区
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci commit system

# 重启网络服务
/etc/init.d/network restart

exit 0
